config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"

  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  MAILER_FROM_EMAIL = "no-reply@example.com"
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  attr_accessor :current_password

  has_secure_password

  has_many :active_sessions, dependent: :destroy

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
  validates :unconfirmed_email, format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end
  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def confirmed?
    confirmed_at.present?
  end

  def unconfirmed?
    !confirmed?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?
    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_authenticated, only: [:create, :new]
  before_action :authenticate_user!, only: [:edit, :destroy, :update]

  def new
    @user = User.new
  end
  def create
    @user = User.new(create_user_params)
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: "Please check your email for confirmation instructions."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: "Check your email for confirmation instructions."
        else
          redirect_to root_path, notice: "Account updated."
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "Incorrect password"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end
  private

  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation, :unconfirmed_email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="grid grid-cols-1 md:grid-cols-3 gap-16">
  <%= form_with model: @user, url: account_path, html: {class:"flex flex-col justify-center items-center md:col-span-2"}, method: :put do |form| %>
    <h2 class="text-4xl tracking-widest font-normal mt-5 mb-24 text-[#6F1D71]">UPDATE ACCOUNT</h2>
    <%= render partial: "shared/form_errors", locals: { object: form.object } %>
    <div class="relative z-0 mb-6 px-4 md:px-0 w-full group">
      <%= form.email_field :email, disabled:true, class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-gray-200 border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer"%>
    </div>
    <div class="relative z-0 mb-6 px-4 md:px-0 w-full group">
      <%= form.text_field :unconfirmed_email, placeholder:"type your new email if u want" ,class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer"%>
    </div>
    <div class="relative z-0 mb-6 px-4 md:px-0 w-full group">
      <%= form.password_field :password, placeholder:"Password (leave blank if you don't want to change it)", class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer" %>
    </div>
    <div class="relative z-0 mb-6 px-4 md:px-0 w-full group">
      <%= form.password_field :password_confirmation, placeholder:"type your password again", class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer" %>
    </div>
    <div class="h-2 w-full px-4 md:px-0 bg-[#6F1D71] border border-[#6F1D71] rounded-3xl mt-16"></div>
    <div class="relative z-0 mb-6 px-4 md:px-0 w-full group mt-4">
      <%= form.password_field :current_password, required: true, placeholder:"*Current password (we need your current password to confirm your changes)", class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer" %>
    </div>
    <%= form.submit "Update Account", class:"text-white font-semibold text-lg text-center py-3  px-24 border border-1 border-[#6F1D71] bg-[#6F1D71] rounded-3xl hover:cursor-pointer hover:bg-[#7b2496] ease-in duration-200" %>
    <%= link_to 'back', root_path, class:"text-[#6F1D71] text-xl hover:text-[#9a3cbc] mt-4" %>
  <% end %>


  <div class="md:col-span-1 overflow-y-auto">
    <% if @active_sessions.any? %>
      <h2 class="text-xl font-semibold mt-16 mb-6 text-[#6F1D71] text-center">Current Logins</h2>
        <% @active_sessions.each do |session| %>
          <div class="flex flex-col justify-center items-start">
            <div class="mt-2 flex justify-between items-center">
              <%= image_tag "user-agent-icon" %>
              <%if session[:user_agent] %>
                <%= session[:user_agent] %>
              <% else %>
                <%= "unknown" %>
              <% end %>
            </div>
            <div class="mt-2 flex justify-between items-center">
              <%= image_tag "ip-address-icon" %>
              <%if session[:ip] %>
                <%= session[:ip] %>
              <% else %>
                <%= "unknown" %>
              <% end %>
            </div>
            <div class="mt-2 flex justify-between items-center">
              <%= image_tag "created-at-icon" %>
              <%= session[:created_at] %>
            </div>
            <div class="mt-2 flex justify-between items-center">
              <%= link_to "sign out this session", active_session_path(session), class:"text-[#6F1D71] text-xl hover:text-[#9a3cbc] mt-4", data:{turbo_method: :delete} %>
            </div>
        </div>
        <% end %>
      <%= link_to "log out of all other sessions",
                    destroy_all_active_sessions_path, data:{turbo_method: :delete, turbo_confirm: "Are u Sure?"},
                    class:"text-[#6F1D71] text-xl hover:text-[#9a3cbc] mt-4 flex justify-end items-start" %>
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<%= form_with model: @user, url: sign_up_path, html: {class:"flex flex-col justify-center items-center"} do |form| %>
  <h2 class="text-4xl tracking-widest font-normal mt-5 mb-24 text-[#6F1D71]">SIGN UP APP</h2>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div class="relative z-0 mb-6 px-4 md:px-0 w-full md:w-1/2 group">
    <%= form.email_field :email, required:true, placeholder:"type your email", class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer"%>
  </div>
  <div class="relative z-0 mb-6 px-4 md:px-0 w-full md:w-1/2 group">
    <%= form.password_field :password, required:true, placeholder:"type your password", class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer" %>
  </div>
  <div class="relative z-0 mb-6 px-4 md:px-0 w-full md:w-1/2 group">
    <%= form.password_field :password_confirmation, required:true, placeholder:"type your password again", class:"block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-[#6F1D71] appearance-none focus:outline-none focus:ring-0 focus:border-[#AD48C6] peer" %>
  </div>
  <%= form.submit "Sign Up", class:"text-white font-semibold text-lg text-center py-3  px-24 border border-1 border-[#6F1D71] bg-[#6F1D71] rounded-3xl hover:cursor-pointer hover:bg-[#7b2496] ease-in duration-200" %>
  <%= link_to 'log in', login_path, class:"text-[#6F1D71] mt-4 text-xl hover:text-[#9a3cbc]" %>
  <%= link_to 'back', root_path, class:"text-[#6F1D71] text-xl hover:text-[#9a3cbc]" %>
<% end %>