config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"

  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="">
  <%if current_user %>
    <div class="flex flex-col items-end justify-center ml-10">
      <h3 class="text-2xl font-normal text-[#6F1D71]">Welcome <%= current_user.email %></h3>
      <%= link_to "Account", account_path, class:"text-[#6F1D71] mt-4 text-xl hover:text-[#9a3cbc]" %>
      <%= link_to "Logout", logout_path, class:"text-[#6F1D71] text-xl hover:text-[#9a3cbc]", data:{turbo_method: :delete} %>
    </div>
  <%end%>
  <div class="flex justify-center items-start">
    <%= image_tag 'home-header-icon.svg' %>
    <h2 class="text-4xl tracking-widest font-normal mt-5 text-[#6F1D71]">RAILS <br> AUTHENTICATION <br> SYSTEM</h2>
  </div>
  <div>
    <p class="text-2xl font-semibold mx-auto text-center mt-16 md:w-1/2">This is an app for learning how do we build completely rails authentication from scrath </p>
  </div>
  <div class="flex flex-col mt-24 md:w-1/2">
    <%= link_to 'Go to log in page', login_path, class:"text-2xl text-start font-medium text-transparent bg-clip-text bg-gradient-to-r from-[#6F1D71] to-[#D482D6]" %>
    <%= link_to 'Go to sign up page', sign_up_path, class:"text-2xl text-start font-medium text-transparent bg-clip-text bg-gradient-to-r from-[#6F1D71] to-[#D482D6]" %>
  </div>
  <div class="flex mt-40 justify-end items-center">
    <a href="https://github.com/sabricakir/rails_authentication_essence_app" class="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#6F1D71] to-[#D482D6]" target=_blank>Go to source code</a>
  </div>
</div>